[package]
name = "mio-glue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = { version = "1", features = ["uuid"]}
tokio = { version = "1.28", features = ["full"] }
once_cell = "1"
num_cpus = "1.15"
anyhow = "1.0.71"
reqwest = { version = "0.11.18", features = ["json"] }
konst = "0.3.5"
mio-common = {path = "../../common"}