[package]
name = "mio-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
slint = { version = "1.3", features = ["gettext", "log"] }
mio-glue = { path = "glue" }
anyhow = "1.0"
smol = "2.0"
async-compat = "0.2"

[build-dependencies]
slint-build = "1.3"
