[package]
name = "mio-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
slint = { version = "1.3", features = ["gettext", "log"] }
mio-glue = { path = "glue" }
parking_lot = "0.12"

[build-dependencies]
slint-build = "1.3"
