[workspace]
members = [
  "frontend",
  "common",
  "backend",
  "backend/migration",
  "backend/entity",
]
resolver = "2"

[profile.release]
lto = true

[profile.release.package.mio-frontend]
opt-level = "s"
