[package]
name = "miogenes-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7", features = ["http2", "macros", "multipart"] }
axum-server = { version = "0.7", features = ["tls-rustls"] }
dioxus = "0.5"
dioxus-ssr = "0.5.6"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.39", features = ["full"] }
tower-http = { version = "0.5", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
