import { VerticalBox } from "std-widgets.slint";
import { SlintUUID } from "common.slint";

export struct AlbumMetadata {
	img_loaded: bool,
	img: image,
	name: string,
	id: SlintUUID,
}

export global AlbumsCB {
	in property <[AlbumMetadata]> all_albums: [];
	in-out property <bool> albums_setup: false;
}

export component Albums inherits VerticalBox {
	if ! AlbumsCB.albums_setup: Text {text: @tr("Loading...");}
	if AlbumsCB.albums_setup && AlbumsCB.all_albums.length == 0: Text {text: @tr("No albums found in the server. Upload some.");}
}
