// global error stuff
export struct ErrorInfo {
	error: string,
	is_error: bool,
}

export global GlobalError {
	in-out property <ErrorInfo> last_error;
	public function clear_error() {
		last_error.is-error = false;
		last_error.error = "";
	}
}

// toplevel state stuff
export enum TopLevelPage {
	Login,
	Signup,
	Ready,
	UploadFolders,
}

export global TopLevelCB {
	in-out property <TopLevelPage> page_t: TopLevelPage.Login;
}

// uuid convs
export struct SlintUUID {
	id: string
}
