import { ListView, HorizontalBox, Button, VerticalBox } from "std-widgets.slint";
export struct DirItem {
    is_dir: bool,
    name: string,
}

export global FolderSelectCB {
    in-out property <bool> loaded: false;
    in-out property <[string]> at: [];
    in property <[DirItem]> cwd: [];
    in-out property <string> create_folder_name: "";

    callback setup();
    callback chdir(string);
    callback up();
    callback new_folder(string);
    callback cancel_new_folder();
    callback cancel();
    callback upload([string]);
}

export component UploadFolderSelect {
    ListView {
        for i in FolderSelectCB.cwd: TouchArea {
            clicked => {
                if i.is_dir {
                    FolderSelectCB.chdir(i.name);
                }
            }
            HorizontalBox {
                Text {
                    text: i.name;
                }
            }
        }
    }

    HorizontalBox {
        Button {
            text: "Upload";
            clicked => {
                FolderSelectCB.upload(FolderSelectCB.at);
            }
        }

        Button {
            text: "Go up dir";
            clicked => {
                FolderSelectCB.up();
            }
        }

        Button {
            text: "New Folder";
            clicked => {
                new_folder_name.show();
            }
        }

        Button {
            text: "Cancel";
            clicked => {
                FolderSelectCB.cancel();
            }
        }
    }

    new_folder_name := PopupWindow {
        close_on_click: false;
        max-width:  128px;
        max-height: 64px;

        VerticalBox {
            TextInput {
                text <=> FolderSelectCB.create_folder_name;
            }
            
            HorizontalBox {
                Button {
                    text: @tr("Cancel");
                    clicked => {
                        FolderSelectCB.cancel_new_folder();
                    }
                }
                Button {
                    text: @tr("Cancel");
                    clicked => {
                        FolderSelectCB.new_folder(FolderSelectCB.create_folder_name);
                    }
                }
            }
        }
    }
}
