// Login ui part
import { VerticalBox , LineEdit , HorizontalBox, Button } from "std-widgets.slint";
import { ErrorInfo } from "common.slint";

// PLEASE HELP
// I don't know if this is the best way to do this

global LoginBoxCB {
	in property <bool> url_is_valid: false;
	in property <ErrorInfo> error;
	callback check_url(string);
	callback attempt_login(string, string);
}

component LoginBox inherits HorizontalBox{
	property url_is_valid <=> LoginBoxCB.url_is_valid;
	property error <=> LoginBoxCB.error;
	out property <string> server_url: "";
	out property <string> username: "";
	out property <string> password: "";

	alignment: LayoutAlignment.center;
	
	VerticalBox {
		alignment: LayoutAlignment.center;
		min-width: 320px;

		// credential input
		LineEdit {
			text: server_url;
			placeholder-text: @tr("Server URL");
		}
		if (url-is-valid): LineEdit {
			text: username;
			placeholder-text: @tr("Username");
		}
		if (url-is-valid): LineEdit {
			text: password;
			placeholder-text: @tr("Password");
			input-type: InputType.password;
		}

		// buttons for credential checking
		HorizontalBox {
			alignment: LayoutAlignment.center;

			Button {
				text: @tr("Connect to URL");
				clicked => { LoginBoxCB.check_url(server_url) } 
			}
			if (LoginBoxCB.url-is-valid): Button {
				clicked => { LoginBoxCB.attempt_login(username, password) }
			}
		}
	}
}

export { LoginBoxCB, LoginBox }
