// Login ui part
import { VerticalBox , LineEdit , HorizontalBox, Button } from "std-widgets.slint";
import { ErrorInfo, GlobalError, TopLevelCB, TopLevelPage } from "common.slint";

// PLEASE HELP
// I don't know if this is the best way to do this
global LoginBoxCB {
	in property <bool> url_is_valid: false;
	callback check_url(string);
	callback attempt_login(string, string);
}

component LoginBox inherits HorizontalBox{
	property url_is_valid <=> LoginBoxCB.url_is_valid;
	property error <=> GlobalError.last_error;
	out property <string> server_url: "";
	out property <string> username: "";
	out property <string> password: "";

	alignment: LayoutAlignment.center;
	
	VerticalBox {
		alignment: LayoutAlignment.center;
		min-width: 320px;

		// credential input
		LineEdit {
			placeholder-text: @tr("Server URL");
			edited(x) => { server_url = x }
		}
		if (url-is-valid): LineEdit {
			placeholder-text: @tr("Username");
			edited(x) => { username = x }
		}
		if (url-is-valid): LineEdit {
			placeholder-text: @tr("Password");
			input-type: InputType.password;
			edited(x) => { password = x }
		}

		// buttons for credential checking
		HorizontalBox {
			alignment: LayoutAlignment.center;

			Button {
				text: @tr("Connect to URL");
				clicked => { LoginBoxCB.check_url(server_url) } 
			}
			if (LoginBoxCB.url-is-valid): Button {
				text: @tr("Signup");
				clicked => { TopLevelCB.page_t = TopLevelPage.Signup }
			}
			if (LoginBoxCB.url-is-valid): Button {
				text: @tr("Login");
				clicked => { LoginBoxCB.attempt_login(username, password) }
			}
		}

		if (error.is-error): HorizontalBox {
			Text {
				text: @tr("error:");
			}

			Text {
				text: error.error;
			}
		}
	}
}

export { LoginBoxCB, LoginBox }
