import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";
import { Player } from "player.slint";
import { Albums } from "albums.slint";
import { Upload } from "upload.slint";

enum MainUIPage {
	Player,
	Albums,
	Upload
}

export global MainUICB {
	in property <MainUIPage> page: MainUIPage.Player;
}

component SideBarItem inherits Rectangle {
	property <bool> selected: on_select == MainUICB.page;
	in property <string> name;
	in property <MainUIPage> on_select;
	
	height: 20px;
	background: Palette.background.darker(selected ? 0.3 : 0.2);

	Text {
		text: name;
	}

	TouchArea {
		width: 100%;
		height: 100%;
		clicked => {
			MainUICB.page = on_select;
		}
	}
}

component SideBar inherits Rectangle {
	in property <[{name: string, to: MainUIPage}]> routes;
	in property <string> title;
		
	max-width: 180px;
	background: Palette.background.darker(0.2);

	VerticalBox {
		alignment: LayoutAlignment.start;
		
		Text { 
			text: title;
			font-size: 16px;
		}

		for p in routes : SideBarItem {
			name: p.name;
			on_select: p.to;
		}
	}
	VerticalBox {
		alignment: LayoutAlignment.stretch;
	}
}

export component MainUIBox inherits HorizontalBox {
	property <MainUIPage> page <=> MainUICB.page;
	
	SideBar {
		title: "Miogenes";
		routes: [
			{name: "Player", to: MainUIPage.Player},
			{name: "Albums", to: MainUIPage.Albums},
			{name: "Upload", to: MainUIPage.Upload},
		]; 
	}
	if page == MainUIPage.Player: Player {}
	if page == MainUIPage.Albums: Albums {}
	if page == MainUIPage.Upload: Upload {}
}
