// Top Level. The main window that contains all other ui components
import { LoginBox, LoginBoxCB } from "login.slint";
import { SignupBox, SignupBoxCB } from "signup.slint";
import { MainUIBox } from "mainui.slint";
import { TopLevelCB } from "common.slint";

// callbacks/functions
export { LoginBoxCB, SignupBoxCB, TopLevelCB }

// common
import { ErrorInfo, GlobalError, TopLevelPage } from "common.slint";
export { ErrorInfo, GlobalError, TopLevelPage }

export component TopLevelWindow inherits Window {
	in-out property <TopLevelPage> page_t <=> TopLevelCB.page_t;

	if (page_t == TopLevelPage.Login) : LoginBox {}
	if (page_t == TopLevelPage.Signup) : SignupBox {}
	if (page_t == TopLevelPage.Ready) : MainUIBox {}
}
