// Top Level. The main window that contains all other ui components
import { LoginBox, LoginBoxCB } from "login.slint";
import { SignupBox, SignupBoxCB } from "signup.slint";
import { UploadFolderSelect, FolderSelectCB } from "folderselect.slint";
import { MainUIBox, MainUICB } from "mainui.slint";
import { TopLevelCB } from "common.slint";
import { PlayerCB } from "player.slint";
import { AlbumsCB } from "albums.slint";
import { UploadCB } from "upload.slint";

// callbacks/functions
export { MainUICB, LoginBoxCB, SignupBoxCB, TopLevelCB, PlayerCB, AlbumsCB, UploadCB, FolderSelectCB }

// common
import { ErrorInfo, GlobalError, TopLevelPage, SlintUUID } from "common.slint";
export { ErrorInfo, GlobalError, TopLevelPage, SlintUUID }

export component TopLevelWindow inherits Window {
	in-out property <TopLevelPage> page_t <=> TopLevelCB.page_t;

	if (page_t == TopLevelPage.Login) : LoginBox {}
	if (page_t == TopLevelPage.Signup) : SignupBox {}
	if (page_t == TopLevelPage.Ready) : MainUIBox {}
	if (page_t == TopLevelPage.UploadFolders) : UploadFolderSelect {}
}
