// Top Level. The main window that contains all other ui components
import { LoginBox } from "login.slint";
import { SignupBox } from "signup.slint";
import { MainUIBox } from "mainui.slint";

export enum TopLevelPage {
	Login,
	Signup,
	Ready
}

export component TopLevelWindow inherits Window {
	in-out property <TopLevelPage> page: TopLevelPage.Login;

	if (page == TopLevelPage.Login) : LoginBox {}
	if (page == TopLevelPage.Signup) : SignupBox {}
	if (page == TopLevelPage.Ready) : MainUIBox {}
}
