[package]
name = "mio_entity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
sea-orm = { version = "0.11.0", features = ["macros"] }
