[package]
edition = "2021"
name = "mio_common"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.147", features = ["derive"]}
uuid = {version = "1.2.2", features = ["serde"]}
