//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3
pub mod album;
pub mod artist;
pub mod cover_art;
pub mod join_playlist_track;
pub mod playlist;
pub mod prelude;
pub mod track;
pub mod user;
pub mod user_token;
