//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::album::Entity as Album;
pub use super::artist::Entity as Artist;
pub use super::cover_art::Entity as CoverArt;
pub use super::join_playlist_track::Entity as JoinPlaylistTrack;
pub use super::playlist::Entity as Playlist;
pub use super::track::Entity as Track;
pub use super::user::Entity as User;
pub use super::user_token::Entity as UserToken;
